#!/usr/bin/env bash

# Colours for output formatting
FGBlue='\e[34m'
FGreset='\e[39m'

# System details
printf "\n"
printf " * Powered/Managed by: {{ motd_information_infrastructure_provider }} - {{ motd_information_infrastructure_manager }}\n"
printf " * OS Distribution:    {{ motd_information_distribution_name }} {{ motd_information_distribution_version }}\n"
printf " * OS Template:        {{ motd_information_template_name }} {{ motd_information_template_version }}\n"

# BAS Systems Inventory
printf "\n"
printf "Machine tracked in the BAS Systems Inventory as '{{ motd_information_systems_inventory_identifer }}'\n"
printf "See ${FGBlue}{{ motd_information_systems_inventory_resource }}/{{ motd_information_systems_inventory_identifer }}${FGreset} for more information\n"
printf "\n"
